-- Users and their videos (PLAN.md Phase 2.2, deliverable D2).
--
-- Ids are UUIDs generated by the application (the defaults only help manual
-- inserts). Timestamps are timestamptz, stored with microsecond precision.

-- +goose Up
CREATE TABLE users (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name          text        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    -- Stored lowercased, so the unique index is case-insensitive.
    email         text        NOT NULL CHECK (email = lower(email) AND email <> ''),
    password_hash text        NOT NULL CHECK (password_hash <> ''),
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE TABLE videos (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_name text        NOT NULL CHECK (original_name <> ''),
    storage_key   text        NOT NULL CHECK (storage_key <> ''),
    zip_key       text,
    status        text        NOT NULL DEFAULT 'PENDING'
                              CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')),
    frame_count   integer     CHECK (frame_count > 0),
    error_message text        CHECK (error_message <> ''),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    -- The invariants of domain.Video: the archive and its frame count exist
    -- exactly when DONE, the error message exactly when FAILED.
    CONSTRAINT videos_done_has_zip
        CHECK ((status = 'DONE') = (zip_key IS NOT NULL AND frame_count IS NOT NULL)),
    CONSTRAINT videos_done_fields_together
        CHECK ((zip_key IS NULL) = (frame_count IS NULL)),
    CONSTRAINT videos_failed_has_error
        CHECK ((status = 'FAILED') = (error_message IS NOT NULL))
);

-- GET /api/v1/videos: the caller's videos, newest first (id as tiebreak).
CREATE INDEX videos_user_created_idx ON videos (user_id, created_at DESC, id DESC);
-- Workers and reconciliation look videos up by status.
CREATE INDEX videos_status_idx ON videos (status);

-- +goose Down
DROP TABLE videos;
DROP TABLE users;
